<?php
namespace GDO\Audio;

use GDO\Form\GDT_ComboBox;

final class GDT_Instrument extends GDT_ComboBox
{
    public static $INSTRUMENTS = array(
        'afghani_guitar',
        'alghoza',
        'accordion',
        'bagpipes',
        'banjo',
        'bassoon',
        'berimbau',
        'bongo',
        'chimta',
        'cello',
        'clarinet',
        'clavichord',
        'cor_anglais',
        'cornet',
        'cymbal',
        'dhime',
        'didgeridoo',
        'dizi',
        'double_bass',
        'drum_kit',
        'esraj',
        'ektara',
        'erhu',
        'euphonium',
        'fiddle',
        'flute',
        'french_horn',
        'ghatam',
        'glass_harmonica',
        'glockenspiel',
        'gong',
        'acoustic_guitar',
        'bass_guitar',
        'electric_guitar',
        'electric_bass_guitar',
        'guqin',
        'guzheng',
        'hang',
        'harmonica',
        'harmonium',
        'harp',
        'harpsichord',
        'hammered_dulcimer',
        'hulusi',
        'hurdy_gurdy',
        'indian_banjo',
        'jews_harp',
        'kalimba',
        'lute',
        'lyre',
        'mandolin',
        'marimba',
        'melodica',
        'oboe',
        'ocarina',
        'octobass',
        'organ',
        'otamatone',
        'oud',
        'pan_pipes',
        'panduri',
        'pennywhistle',
        'piano',
        'piccolo',
        'pipa',
        'pungi',
        'rabab_or_rubab',
        'recorder',
        'sarangi',
        'sarinda',
        'suroz',
        'sursinger',
        'santoor',
        'sarod',
        'saxophone',
        'shehnai',
        'sheng',
        'sitar',
        'steelpan',
        'suona',
        'synthesizer',
        'tabla',
        'tambourine',
        'timpani',
        'triangle',
        'trombone',
        'trumpet',
        'theremin',
        'thundertube',
        'tuba',
        'ukulele',
        'viola',
        'violin',
        'vocal_cords',
        'whamola',
        'xylophone',
        'zither',
    );
    
    public function defaultLabel() { return $this->label('instrument'); }
    
    public function __construct()
    {
//         $this->enumValues(...self::$INSTRUMENTS);
//         $this->emptyValue("0");
//         $this->emptyLabel('not_specified');
        $this->notNull();
        $this->completionHref(href('Audio', 'CompleteInstrument'));
    }
    
}
